### ISSUE TITLE
Heimat der entstehenden Methoden

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#10]
Verständnisfrage: Die entstehenden Methoden sind Teil eines auf Maven publizierten Jar, und werden hier als Test-Dependency referenziert?

**Comment by domi-b** [comment]
Die neuen Methoden werden hauptsächlich im [Testbed-Runner](https://github.com/GeoWerkstatt/interlis-testbed-runner) umgesetzt, welcher hier über maven als Test-Dependency referenziert wird.
Zudem kann es Methoden geben, welche direkt hier umgesetzt werden, z.B. falls sie ausserhalb des Testbeds nicht wiederverwendbar sind.
