### ISSUE TITLE
Vier tests schlagen fehl

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#15]
BefundSteinBlockschlagImAbklPerimeterTest > checkConstraint() FAILED
    org.opentest4j.AssertionFailedError at BefundSteinBlockschlagImAbklPerimeterTest.java:15

BefundSteinBlockschlagJaehrlichkeit30Test > checkConstraint() FAILED
    org.opentest4j.AssertionFailedError at BefundSteinBlockschlagJaehrlichkeit30Test.java:15

BefundSteinBlockschlagTest > checkConstraint() FAILED
    org.opentest4j.AssertionFailedError at BefundSteinBlockschlagTest.java:15

FliessrichtungspfeilZuHauptprozessTest > checkConstraint() FAILED
    org.opentest4j.AssertionFailedError at FliessrichtungspfeilZuHauptprozessTest.java:15

14 tests completed, 4 failed

**Comment by olivergrimm** [comment]
kannst Du mir die entsprechenden Output-Erzeugnisse (Verzeichnisse) durchgeben? (zip)

**Comment by olivergrimm** [comment]
@ojeker Hast Du in der Konsole Angaben darüber, ob der Merge der XTF-Files in diesen Fällen nicht klappt? Bei uns werden diese 4 Failcases validiert.
