### ISSUE TITLE
No object found with OID (CheckBefundSpontaneRutschungKeineUeberragung)

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#16]
Stimmt da etwas noch nicht mit dem XTF erstellen?

(Siehe volles log beiliegend)
[Failcase-1-merged.log](https://github.com/sogis/natgef-testbed/files/15151065/Failcase-1-merged.log)

**Comment by olivergrimm** [comment]
diesen Fehler kann ich nachvollziehen. Ich passe das entsprechende Failcase.xtf an.
