### ISSUE TITLE
Falsches Modell referenziert in metaConfig ini

### ISSUE THREAD

**Issue by edigonzales** [sogis/natgef-testbed#22]
https://github.com/sogis/natgef-testbed/blob/main/TestSuite-1/models/SO_AFU_Naturgefahren_20240515-gretl-meta.ini#L2

Hier muss man das "normale" Geodatenmodell referenzieren. Das Validierungsmodell wird im ini-Files mit "additionalModels" referenziert.

**Comment by ojeker** [comment]
Alles klar - Danke
