### ISSUE TITLE
Constraints mit Funktion IsInsideAreaByCode(...) schlagen bei Verschachtelungen vom mehr als zwei Polygonen fehl

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#23]
Das funktioniert nicht (Constraint schlägt falscherweise fehl):

![image](https://github.com/sogis/natgef-testbed/assets/24891004/39108414-6747-477a-818d-b5f84616afe4)

das hingegen funktioniert (Constraint ist erfüllt)

![image](https://github.com/sogis/natgef-testbed/assets/24891004/a9ec8cb6-8e18-460d-91c8-cb3522914d6c)

Provozierte Fehlermeldung:

    ...
    Info: validate set constraint SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch.CheckBefundUeberschwemmungDynamischKeineUeberragung...
    Error: line 14: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 51: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
    Error: line 15: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 52: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
    Error: line 16: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 53: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
    ...

Zip mit vollem Log und Testdaten:
[dreier_fehler.zip](https://github.com/sogis/natgef-testbed/files/15464410/dreier_fehler.zip)

**Comment by olivergrimm** [comment]
@ojeker Ich konnte den falschen Fehler weder mit 1.14.1 noch mit 1.14.2 reproduzieren. Ich sehe es schon richtig, dass in dreier.xtf der Fehler enthalten ist?
[oli-dreier.log](https://github.com/sogis/natgef-testbed/files/15482224/oli-dreier.log)

Mit der folgenden Konstellation erhalte ich den erwarteten Fehler:
![image](https://github.com/sogis/natgef-testbed/assets/3465512/8de0abeb-c9a2-4687-938b-5474412434cb)

Der Umstand, dass im obigen Beispiel im Log drei Fehler auftauchen (obwohl eigentlich nur zwei Objekte untereinander fehlerhaft sind) ist eine aktuelle (mangelhafte) Eigenschaft vom ilivalidator bei SET CONSTRAINTS und benutzerspezifischen Fehlermeldungen.

**Comment by ojeker** [comment]
Hmm - Versionspuff..?

Referenzierte Bibliotheken:

    <dependency>
        <groupId>ch.geowerkstatt.ilivalidator.extensions.functions</groupId>
        <artifactId>geow-interlis-functions</artifactId>
        <version>0.2.0</version>
    </dependency>
    <dependency>
        <groupId>ch.geowerkstatt.ilivalidator.extensions.functions</groupId>
        <artifactId>interlis-functions-ngk-so</artifactId>
        <version>1.0.0</version>
    </dependency>

**Comment by olivergrimm** [comment]
ich verwende exakt dieselben Versionen.

**Comment by olivergrimm** [comment]
Aktuell bemängelt die IsInside-Methode und der Constraint schlägt fehl bei der folgenden Situation, wo die beiden Geometrien gemeinsame Stützpunkte haben. 
![image](https://github.com/sogis/natgef-testbed/assets/3465512/36bd7e4f-077d-4ec3-9595-78474ba5089c)

So wie ich die [JTS Doku](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#contains(org.locationtech.jts.geom.Geometry)) lese, ist dies bei der Verwendung von covers() wie erwartet und wäre bei contains() toleriert.

**Comment by olivergrimm** [comment]
das [ursprünglich geschilderte Problem](https://github.com/sogis/natgef-testbed/issues/23#issue-2320169057) ist nicht mehr nachvollziehbar.
Ist das korrekt, @ojeker ?

**Comment by ojeker** [comment]
Jein - es ist auf dem Testbed nicht rekonstruierbar. Darum können wir diesen Aspekt bis auf Weiteres "vergessen".

**Comment by ojeker** [comment]
Funktioniert mit Version interlis-functions-ngk-so:1.0.1
