### ISSUE TITLE
 IsInsideAreaByCode(...): Räumliche Beziehung Gebietseinteilung und Hochzeitstorte

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#26]
Ich glaube, ich konnte das Problem aus dem Issue #23 nun konkretisieren.

Versuch der verständlichen Beschreibung mittels der Begriffe "Gebietseinteilung" und "Hochzeitstorte" und diesem Screenshot:

![image](https://github.com/sogis/natgef-testbed/assets/24891004/7ffed4a9-8ce8-431a-9923-c98561becc41)

* rot_stark_30 bildet zusammen mit blau_mittel_30 eine Gebietseinteilung, sprich das grössere blau_mittel_30 ist ein Hufeisen
* Diese Gebietseinteilung bildet zusammen mit rot_stark_100 eine Hochzeitstorte. Sprich die Gebietseinteilung darf rot_stark_100 nicht überlappen.

Diese Kombination der räumlichen Beziehungen triggert den Constaint, obwohl sie in Ordnung wäre.

Inhalt des Zip's der Beilage jeweils als Xtf mit Screenshot:
* simple_notouch: Räumliche Beziehung nur "Hochzeitstorte" -> Funktioniert
* complex_notouch: Räumliche Beziehung Gebietseinteilung und Hochzeitstorte (Thema dieses Issue)
* complex_touch: Räumliche Beziehung Gebietseinteilung und Hochzeitstorte. Zusätzlich Cornercase mit gemeinsamer Kante

[testcases.zip](https://github.com/user-attachments/files/15783145/testcases.zip)

**Comment by patrickackermann** [comment]
Die Funktion [NGK_SO_FunctionsExt.IsInsideAreaByCode](https://github.com/GeoWerkstatt/interlis-functions-ngk-so/blob/main/src/model/NGK_SO_FunctionsExt_23.ili)
> Prüft bei der Objektmenge, dass die gemäss dem geordneten Enum oder aufsteigend sortierten numerischen Wert jeweils kleineren Flächen innerhalb der grösseren Flächen liegen. Die Sortierung des Enums muss von der kleinsten zur grössten Fläche erfolgen (mittels ORDERED).


Gemäss enum [SO_AFU_Naturgefahren_20240515.Befunde.IWCodeStandard](https://geo.so.ch/models/AFU/SO_AFU_Naturgefahren_20240515.ili) muss das Polygon von `blau_mittel_30` das Polygon von `rot_stark_100` einschliessen. Das macht es hier aber offensichtlich nicht und daher gibt es einen Fehler.

Mit der verbesserten Fehlermeldung (https://github.com/sogis/natgef-testbed/issues/25) sieht das log jetzt folgendermassen aus:
```
Info: validate set constraint SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch.CheckBefundUeberschwemmungDynamischKeineUeberragung...
Error: line 38: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 14: IsInsideAreaByCode found an invalid overlap between code 'rot_stark_100' and 'blau_mittel_30'. The offending geometry is inside this envelope: POLYGON ((2609990 1252460, 2609990 1252520, 2610050 1252520, 2610050 1252460, 2609990 1252460))
Error: line 38: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 14: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
Error: line 39: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 15: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
Error: line 40: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 86: Die Gesamtausdehnung der kleineren Jährlichkeit überragt diejenige der grösseren Jährlichkeit.
```

**Comment by ojeker** [comment]
@patrickackermann Danke für die Rückmeldung. Die Reihenfolge im Modell spiegelt die "Benutzererwartung". Werde diese zurückstellen und melde mich wieder.

Zu den Logs siehe in #25.

**Comment by ojeker** [comment]
Habe das Beispiel modifiziert gemäss meinem Verständnis der Prüflogik und der aktuellen Codeliste:

        IWCodeStandard = (
          rot_stark_30,
          rot_stark_100,
          rot_stark_300,
          rot_mittel_30,
  
          blau_mittel_30,
          blau_mittel_100,
          blau_mittel_300,
          gelb_mittel_300,
          
          blau_schwach_30,
          blau_schwach_100,
          gelb_schwach_100,
          gelb_schwach_300,
  
          restgefaehrdung_stark,
          restgefaehrdung_mittel,
          restgefaehrdung_schwach
        ) ORDERED;

![image](https://github.com/sogis/natgef-testbed/assets/24891004/4d3b4bbe-70ec-4dbf-bb76-cd65e9601ae2)

So validiert es. Die Reihenfolge der Codes soll so zwei Ordnungssystemen gehorchen:

1.  Erwartung der Benutzer (Was kommt im Dropdown an welcher Stelle
2.  Erwartung der Funktion, damit diese korrekt funktioniert

Wegen 2. auf 1. zu verzichten war nicht die Idee. Kläre das mit den Benutzern und melde mich wieder.

**Comment by patrickackermann** [comment]
> So validiert es.

Das kann ich so nicht reproduzieren, ich bekomme auch mit anderer Sortierung einen Validierungsfehler. _(Dies entspricht meiner erwartung gemäss funktionsweise von IsInsideAreaByCode)_

**Comment by edigonzales** [comment]
@patrickackermann @ojeker Vielleicht nicht relevant für dieses Issue, aber die Unterstützung von ORERED ist nicht wirklich perfekt: 
- https://github.com/claeis/ili2db/issues/526
- https://github.com/claeis/ili2db/issues/445
- https://github.com/claeis/umleditor/issues/79

**Comment by ojeker** [comment]
Funktioniert in Testbett mit interlis-functions-ngk-so:1.0.1
