### ISSUE TITLE
IsInsideAreaByCode(...): Fehlerhafte Gruppierung nach Reihenfolge

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#27]
Einziger Unterschied zum Testfall in Issue #26 unten ist die Aufteilung der gelb_schwach_300 Fläche von vorher einem in neu zwei Polygone (oben und unten). Dies führt zu einem Validierungsfehler.

![image](https://github.com/sogis/natgef-testbed/assets/24891004/a83527d3-c90f-4ce0-8da0-513100980d31)

XTF (Mit weiteren, aber validierenden Testdaten): 
[export_two_outer.zip](https://github.com/user-attachments/files/15868688/export_two_outer.zip)

**Comment by patrickackermann** [comment]
Der Validierungsfehler ist:
```
Info: validate set constraint SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch.CheckBefundUeberschwemmungDynamischKeineUeberragung...
Error: line 38: SO_AFU_Naturgefahren_20240515.Befunde.BefundUeberschwemmungDynamisch: tid 14: IsInsideAreaByCode found an invalid overlap between code 'blau_schwach_100' and 'gelb_schwach_100'. The offending geometry is inside this envelope: POLYGON ((2610000 1252470, 2610000 1252510, 2610040 1252510, 2610040 1252470, 2610000 1252470))
```

`blau_schwach_100` und `gelb_schwach_100` führen zum Fehler. Das `gelb_schwach_300` unterteilt ist hat keinen Einfluss. Hier noch graphisch dargestellt, was der constraint erwartet:
![image](https://github.com/sogis/natgef-testbed/assets/26359070/371fd65e-8e3c-4805-ab22-40a00305caaa)
_Die Fläche `blau_schwach_100` muss vollständig in der Fläche `gelb_schwach_100` sein, die wiederum vollständig in der Fläche `gelb_schwach_300` sein muss_

**Comment by ojeker** [comment]
@patrickackermann Danke für die Analyse. Das Verhalten des Constraint ist damit fachlich noch nicht korrekt. Damit haben wir ein "Informationsloch" eingegrenzt, welches wir an der gleich folgenden Besprechung schliessen.

**Comment by ojeker** [comment]
Version?

Execution failed for task ':app:compileTestJava'.
> Could not resolve all files for configuration ':app:testCompileClasspath'.
   > Could not find ch.geowerkstatt.ilivalidator.extensions.functions:interlis-functions-ngk-so:1.0.1-Snapshot.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/ch/geowerkstatt/ilivalidator/extensions/functions/interlis-functions-ngk-so/1.0.1-Snapshot/interlis-functions-ngk-so-1.0.1-Snapshot.pom
       - https://jars.interlis.ch/ch/geowerkstatt/ilivalidator/extensions/functions/interlis-functions-ngk-so/1.0.1-Snapshot/interlis-functions-ngk-so-1.0.1-Snapshot.pom
     Required by:
         project :app

**Comment by patrickackermann** [comment]
@ojeker Ich habe einen Release von _interlis-functions-ngk-so_ erstellt.
```
implementation 'ch.geowerkstatt.ilivalidator.extensions.functions:interlis-functions-ngk-so:1.0.1'
```

**Comment by ojeker** [comment]
@patrickackermann Danke. Besprochen hatten wir eine Versionserhöhung, um Cache-Probleme zu vermeiden. Rufe an, falls diese nun eintreten.

**Comment by patrickackermann** [comment]
@ojeker Entschuldigung, die Version hat sich erhöht aber ich hatte die Falsche version kopiert. Ich habe meinen Kommentar angepasst.

**Comment by ojeker** [comment]
@patrickackermann OK :)

**Comment by ojeker** [comment]
Funktioniert mit Version interlis-functions-ngk-so:1.0.1
