### ISSUE TITLE
IsInsideAreaByCode(...): Fehlermeldung  "getX called on empty Point"

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#29]
Bei gewissen Geometrien schlägt die Funktion noch mit der folgenden Fehlermeldung fehl:

![image](https://github.com/user-attachments/assets/2c591d40-e44f-4674-8c60-019da66b79e5)

Nachvollziehbar mit dem beliegenden xtf (in zip). 
[128_Himmelried_2023.zip](https://github.com/user-attachments/files/16522782/128_Himmelried_2023.zip)

Fehleranalyse von Stefan:

****************************************

Hallo Doris

Es braucht wohl Geowerkstatt. Meine Recherche hat ergeben, dass es bei einer dieser Zusatzfunktionen passiert: https://github.com/GeoWerkstatt/interlis-functions-ngk-so/blob/main/src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/ngk/IsInsideAreaByCodeIoxPlugin.java#L99

Der Zentroid ist null. Ebenso ist die "offendingGeometry" null, die aus der Difference von "current" und "next" gerechnet wird. Und wenn diese Difference null ist, ist der Zentroid null und dann geht halt auch "getX()" nicht. 

Ich weiss nicht, ob es falsch ist "difference" zu berechnen (und eher intersection besser wäre?) oder hier nur ein edge case vorliegt. Jedenfalls kommt das Problem mehrfach vor. Ich habe mir die beiden Geometrien als Text ausgeben lassen und dann in QGIS importiert. Siehe Anhang.

Oder eventuell ist "contains" schon falsch und es müsste within sein. Siehe z.B. https://en.wikipedia.org/wiki/DE-9IM. Das müsste das Fach bestimmen, was richtig ist. So wie ich es lese, dürfen bei contains keine Punkte auf der Umrandung gleich sein ("no points of b lie in the exterior of a"). Oder lese ich das falsch?

Ich habe getestet, was passiert, wenn ich die "next"-Geometrie vor der contains-Prüfung einen Zentimeter buffere. Dann flutschts durch. Tendiere auf edge case. Löst jetzt leider das Problem nicht.

Gruess
Stefan

**Comment by patrickackermann** [comment]
Ich habe den Fehler analysiert und folgendes minimales XTF erstellt, das den Fehler zeigt:
[128_Himmelried_2023_edge_case.zip](https://github.com/user-attachments/files/16609412/128_Himmelried_2023_edge_case.zip)

Der rote Punkt 3 liegt auf der blauen Kante 3 - 4. Beim `contains` check gibt JTS `false` zurück also ein fehlerhafter Overlap, wenn dann aber die Fehlerhafte Geometrie berechnet wird, ist diese leer.
![image](https://github.com/user-attachments/assets/670837d7-e202-4a29-98bb-0878df7aa771)

Ich sehe grad keine Möglichkeit mit JTS den Punkt zu berechnen der den Edge Case Verursacht.

**Comment by ojeker** [comment]
Hoi Patrick - Hab dich per Tel. nicht erreicht. Kannst du mir zurückrufen? Danke.

**Comment by ojeker** [comment]
Hatte im Nachgang noch die folgende Idee aufgrund der Analyse von Stefan: Falls die Fehler-Geometrie leer ist, die Difference mit "Next-Geometrie + 1 cm Puffer" berechnen. Das ist für die Benutzer immer noch bei Weitem genügend Nahe, um das Problem zu finden.

**Comment by patrickackermann** [comment]
Ein solcher Puffer könnte dann halt viele _false positives_ generieren, z.B. dort wo die Linien aufeinander liegen und eigentlich in Ordnung wären.

**Comment by ojeker** [comment]
Punkt auf Fläche via: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/InteriorPointArea.html

Angepasste Fehlermeldung: "IsInsideAreaByCode(...): Overlap or topo error between code '{0}' and '{1}' near coordinates {2}",

**Comment by ojeker** [comment]
Danke Patrick für die Anpassung. Über das nun noch offene Review haben wir das letzte Mal nicht gesprochen. Kann ich am Mittwoch die neue Version ins Testbett integrieren (Sprich: Review durch, neue Version ist auf Maven verfügbar)?

**Comment by patrickackermann** [comment]
@ojeker Die neue Version der [interlis-functions-ngk-so](https://github.com/GeoWerkstatt/interlis-functions-ngk-so) ist auf Maven released.

**Comment by ojeker** [comment]
@patrickackermann Super - Danke. Integriere heute in Testbed. Kommende Woche dann Tests mit weiteren Daten.
