### ISSUE TITLE
Fehlende Constraints auf konkreten Befund-Klassen?

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#4]
Siehe Kommentare zum Pull-Request https://github.com/sogis/p-naturgefahren-ili/pull/5

Zur Info: Auf dem repo p-naturgefahren-ili gibt es nur noch den main Branch. Auf diesem arbeite ich parallel zu diesem Issue am ili weiter, um die Kommentare zu bereinigen.

**Comment by olivergrimm** [comment]
see: https://github.com/sogis/p-naturgefahren-ili/commit/5161a9e391ca7cb2e5b43201600a8a3b7a33f704 #
