### ISSUE TITLE
Constraint-View noch verwendet?

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#5]
Die Verwendung der folgenden View habe ich nicht gefunden / verstanden:

    /** Hilfsview für Constraint */
    VIEW Helper_BefundUeberschwemmung
      UNION OF BUsD ~ BefundUeberschwemmungDynamisch, BUsS ~ BefundUeberschwemmungStatisch;
      =
      Geometrie: Einzelflaeche;
    END Helper_BefundUeberschwemmung;

**Comment by olivergrimm** [comment]
Der View war bereits Teil des "Pilotmodells", war bereits da nur Platzhalter und wird auch aktuell nicht benötigt. @ojeker Soll ich ihn in https://github.com/sogis/p-naturgefahren-ili/blob/main/modell/SO_AFU_Naturgefahren_20240311.ili rauswerfen oder machst Du das?
