### ISSUE TITLE
Modellrepo für "NGK Functions Ext" (GeoW Functions Ext)

### ISSUE THREAD

**Issue by ojeker** [sogis/natgef-testbed#6]
Hoi Oliver

Dumm von mir - die folgende Frage wollte ich vorhin auch noch besprechen. Geht aber glaubs auch per Issue.

Es betrifft die Model Repo's für die Funktionsmodelle:

- GeoW_FunctionsExt
- NGK_SO_FunctionsExt

GeoW_FunctionsExt hat schon ein Model-Repository und wird damit gefunden, falls es in irgendeinem Modell referenziert ist?
NGK_SO_FunctionsExt braucht noch eine Heimat...? Dann pushe ich dieses auf geo.so.ch/models (Unser Modell-Repo)?

**Comment by olivergrimm** [comment]
Das Repo mit NGK_SO_FunctionsExt ist dieses: https://github.com/GeoWerkstatt/interlis-functions-ngk-so
